### ISSUE TITLE
Not supported in node version 4.2.4

### ISSUE THREAD

**Issue by mannu1200** [buglabs/node-xml2json#105]
$ n use 4.2.4
> var a = require('xml2json');
Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at bindings (/home/mannumalhotra/code/a/node_modules/xml2json/node_modules/node-expat/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/mannumalhotra/code/a/node_modules/xml2json/node_modules/node-expat/lib/node-expat.js:4:32)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
>

**Comment by mannu1200** [comment]
After rebuilding, it is giving this error->

Error: Module version mismatch. Expected 46, got 47.
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at bindings (/home/mannumalhotra/code/fulfillment-recharge/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/mannumalhotra/code/fulfillment-recharge/node_modules/node-expat/lib/node-expat.js:4:32)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

**Comment by mannu1200** [comment]
recompiling or reinstalling it with newer version solved the porblem.
