### ISSUE TITLE
Error: Module did not self-register.

### ISSUE THREAD

**Issue by samtajoshi20** [buglabs/node-xml2json#114]
START RequestId: 0f5df089-11bb-11e6-8280-8328c6dcc8fd Version: $LATEST
2016-05-04T05:42:59.864Z	0f5df089-11bb-11e6-8280-8328c6dcc8fd	Loading function
2016-05-04T05:43:05.546Z	0f5df089-11bb-11e6-8280-8328c6dcc8fd	Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at bindings (/var/task/node_modules/xml2json/node_modules/node-expat/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/var/task/node_modules/xml2json/node_modules/node-expat/lib/node-expat.js:4:32)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
END RequestId: 0f5df089-11bb-11e6-8280-8328c6dcc8fd
REPORT RequestId: 0f5df089-11bb-11e6-8280-8328c6dcc8fd	Duration: 5973.29 ms	Billed Duration: 6000 ms 	Memory Size: 128 MB	Max Memory Used: 36 MB	
Process exited before completing request

**Comment by c4milo** [comment]
npm rebuild should fix it.
