### ISSUE TITLE
Not supported in node version 6.0

### ISSUE THREAD

**Issue by muraliselvaraj** [buglabs/node-xml2json#117]
Error: Module version mismatch. Expected 48, got 47.

**Comment by c4milo** [comment]
Did you recompile the module after upgrading node?

**Comment by muraliselvaraj** [comment]
Yes, I did but still I am getting same error.

**Comment by muraliselvaraj** [comment]
Also can you check your .travis.yml file, there node 6.0 and node 4.X some of the versions are missed.

**Comment by KidA001** [comment]
Any update on this? Also not able to run it in node 6

**Comment by BlueHotDog** [comment]
:( 👍

**Comment by c4milo** [comment]
I will look into this soon.

**Comment by muraliselvaraj** [comment]
Is there any update?
Thanks in Advance.

**Comment by HoosierMike** [comment]
Yep, were dead in the water, npm won't even pull it down correctly in Node 6

```
C:\github\OHEP\Server\node_modules\node-expat>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:117:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\github\OHEP\Server\node_modules\node-expat
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
ohep.server@1.0.0 C:\github\OHEP\Server
+-- joi@6.10.1  extraneous
`-- xml2js@0.4.17  extraneous

npm WARN ohep.server@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "xml2json"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! node-expat@2.3.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-expat@2.3.15 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-expat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-expat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-expat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\github\OHEP\Server\npm-debug.log

C:\github\OHEP\
```Server>

**Comment by woshizoufeng** [comment]
Maybe u should check ur gcc version.I try to install the module failed under gcc 4.4.
But when I update gcc to version 4.8. It work.

**Comment by c4milo** [comment]
@HoosierMike it seems, in your case, you are missing python in your system.

**Comment by creeperyang** [comment]
Failed install to win7,  `node@6.2.1, npm@3.9.3`:

```bash
...
node-expat@2.3.15 install: `node-gyp rebuild`
Exit status 1

Failed at the node-expat@2.3.15 install script 'node-gyp rebuild`
...
```

Note: success on Mac...

**Comment by c4milo** [comment]
@creeperyang what version of Visual Studio do you have?

**Comment by c4milo** [comment]
@creeperyang, please refer to https://github.com/nodejs/node-gyp/issues/629#issuecomment-225578519 and see if you can solve your compiler issue.

**Comment by creeperyang** [comment]
VS2010

I installed `windows-build-tools`, and it didn't help.

Only update to VS2015?
