### ISSUE TITLE
xml2json does not work on electron

### ISSUE THREAD

**Issue by LukasBombach** [buglabs/node-xml2json#118]
I am trying to use `node-xml2json` on GitHub's Electron but I get the error

> Uncaught TypeError: Path must be a string. Received undefined

that is thrown at line 1

```javascript
var expat = require('node-expat');
```

my code works fine when I run it through node directly on the console.

**Comment by LukasBombach** [comment]
Oh sorry, it seems like the error occurs within `node-expat `, so I guess they need to fix it.

**Comment by c4milo** [comment]
Were you following
http://electron.atom.io/docs/tutorial/using-native-node-modules/?

**Comment by supermoney1709** [comment]
Im having the same issue, code runs fine without electron but as soon as I include it it fails and gives me this: 

`> electron js/index.js


App threw an error during load
Error: A dynamic link library (DLL) initialization routine failed.
\\?\D:\Web Dev\Jonar\xliff-translation\node_modules\node-expat\build\Release\node_expat.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at bindings (D:\Web Dev\Jonar\xliff-translation\node_modules\bindings\bindings.js:76:44)
`

**Comment by j-norwood-young** [comment]
I'm getting this error in Electron: 

`bindings.js:83` Uncaught Error: Module version mismatch. Expected 50, got 47.`

The problem is in the bindings library, and seems related to: https://github.com/sofroniewn/electron-johnny-five-examples/issues/4

**Comment by c4milo** [comment]
Did you run `./node_modules/.bin/electron-rebuild` after running `npm install`?

**Comment by j-norwood-young** [comment]
Yes. It didn't seem to do anything useful. I also deleted my node_modules and ran a fresh `npm install`. I tried loading the `node-expat` library directly and got the same error, so it's definitely upstream. My requirement is pretty simple, so in the end I used https://github.com/eugene-moroz/xml-json-parser which has no dependencies (or documentation).

**Comment by c4milo** [comment]
http://stackoverflow.com/questions/15584529/module-version-mismatch-expected-11-got-1

**Comment by wxplovecc** [comment]
cd ./node_modules/node-expat
and then 
node-gyp rebuild --target=1.7.8 --arch=x64  --dist-url=https://atom.io/download/electron
rebuild 
[see electron doc](https://www.electronjs.org/docs/tutorial/using-native-node-modules)

if you use webpack to bundle
[some posts](http://jlongster.com/Backend-Apps-with-Webpack--Part-I) or use [ webpack-node-externals](https://webpack.js.org/configuration/externals/)
