### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by cariai** [buglabs/node-xml2json#137]
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/avanguard/cti/node_modules/xml2json/lib/xml2json.js:3:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by c4milo** [comment]
Hi @cariai!, I'm sorry you ran into that error, what Node version were you using?

**Comment by cariai** [comment]
# node -v
v0.10.25

**Comment by c4milo** [comment]
Is there any chance to upgrade it to the LTS version? I think it is v6.9.4
