### ISSUE TITLE
Error: `make` failed with exit code: 2

### ISSUE THREAD

**Issue by bhushankumarl** [buglabs/node-xml2json#146]
make: Leaving directory `/home/travis/build/bhushankumarl/amazon-mws/node_modules/xml2json/node_modules/node-expat/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/versions/node/v4.8.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 4.8.12-040812-generic
gyp ERR! command "/home/travis/.nvm/versions/node/v4.8.4/bin/node" "/home/travis/.nvm/versions/node/v4.8.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/travis/build/bhushankumarl/amazon-mws/node_modules/xml2json/node_modules/node-expat
gyp ERR! node -v v4.8.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm ERR! Linux 4.8.12-040812-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v4.8.4/bin/node" "/home/travis/.nvm/versions/node/v4.8.4/bin/npm" "install"
npm ERR! node v4.8.4
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! node-expat@2.3.16 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-expat@2.3.16 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-expat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-expat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls node-expat
npm ERR! There is likely additional logging output above.

**Comment by caicaishmily** [comment]
I have a same error

**Comment by ejames17** [comment]
@bhushankumarl  @caicaishmily  i have the same issue +1

**Comment by Matthbo** [comment]
If you use ubuntu please install build-essential
`sudo apt install build-essential`
This might also work with other linux distro's
