### ISSUE TITLE
npm ERR! node-expat@2.3.18 install: `node-gyp rebuild`

### ISSUE THREAD

**Issue by AbhishekEM** [buglabs/node-xml2json#190]
Team,

I am getting the above error when I am trying to install xml2json in MacOs Catalina 10.15.3.
Can someone please help me out to fix this issue?

> node-expat@2.3.18 install /Users/aem/CPP/node_modules/node-expat
> node-gyp rebuild

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.3.0
gyp ERR! command "/usr/local/Cellar/node@10/10.19.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/aem/CPP/node_modules/node-expat
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v5.0.7
gyp ERR! not ok 
npm WARN cpp@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-expat@2.3.18 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-expat@2.3.18 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aem/.npm/_logs/2020-02-20T06_54_24_818Z-debug.log

**Comment by leonakao** [comment]
Same problem on win 10 Pro

**Comment by wxm45337** [comment]
Same problem on win Linux

**Comment by wxm45337** [comment]
Same problem on Linux

**Comment by sorieil** [comment]
Same plroblem on Ubuntu(wsl2)

**Comment by ogrotten** [comment]
Same problem still.

**Comment by ogrotten** [comment]
I believe that this has to do with _[Windows Build Tools](https://www.npmjs.com/package/windows-build-tools)_ 

* Start `Powershell as Administrator`
* `yarn global add windows-build-tools`

Then try it. I got past this error, but ultimately it didn't work for me as I got a different `node-expat` error (which i will post over there). But it's a different error, so I'm **_hoping_** this is the right track.
